### ISSUE TITLE
Could not find the original system xxxxx in EDSM database

### ISSUE THREAD

**Issue by Pauliakov** [DlljsCodes/exploration-progress#20]
Hello

I am writing to you because I cannot find a solution.
For any system I have now this message.

Impossible to make the plugin work again.
I switched to 1.0.4 but it didn't change either.

Do you have any idea ?

![image](https://user-images.githubusercontent.com/71530380/141282962-5affbc85-ebb0-4a62-a747-ba96574c0e73.png)

**Comment by DlljsCodes** [comment]
I can't seem to reproduce that. Can you perform the following please?

1. In EDMC, go to File -> Settings, go to the Configuration tab and set the Log Level to DEBUG.
2. Go to the Exploration Progress tab, make sure the system names are correct and click OK.
3. Press **Windows Key** + **R**, type in `%TEMP%` and press **Enter**.
4. Find the `EDMarketConnector.log` file and upload it in a new comment here.

I'll take a look at the log file and see what went wrong.

**Comment by Pauliakov** [comment]
Sure, please find attached, thank you for your help 

```
2021-11-14 21:27:06.844 - INFO - 8184:5532:5532 EDMarketConnector.__main__:1844: Startup v5.2.1+b589ac3 : Running on Python v3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:05:41) [MSC v.1929 32 bit (Intel)]
E:D Market Connector 5.2.1+b589ac3
2021-11-14 21:27:06.897 - INFO - 8184:5532:5532 killswitch.fetch_kill_switches:341: Attempting to fetch kill switches
2021-11-14 21:27:07.277 - INFO - 8184:5532:5532 killswitch.parse_kill_switches:404: Kill switches last updated 18 October 2021
2021-11-14 21:27:07.543 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "coriolis" from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
2021-11-14 21:27:07.556 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "eddb" from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
2021-11-14 21:27:07.559 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "eddn" from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
2021-11-14 21:27:07.568 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "edsm" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
2021-11-14 21:27:07.581 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "edsy" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
2021-11-14 21:27:07.586 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "inara" from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
2021-11-14 21:27:07.610 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "EDMC-Screenshot-master" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-master\load.py"
2021-11-14 21:27:08.688 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "EDMCOverlay" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMCOverlay\load.py"
EDMCOverlay: EDMC Ready
Error sending message in plugin_start() : [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée
2021-11-14 21:27:11.184 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "ATEL" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\ATEL\load.py"
2021-11-14 21:27:11.443 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "ATEL-EDMC-latest" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\ATEL-EDMC-latest\load.py"
2021-11-14 21:27:11.445 - ERROR - 8184:5532:5532 plug.Plugin.__init__:62: : Failed for Plugin "ATEL-EDMC-latest"
Traceback (most recent call last):
  File "plug.pyc", line 49, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Paul\\AppData\\Local\\EDMarketConnector\\plugins\\ATEL-EDMC-latest\\load.py'
2021-11-14 21:27:11.447 - ERROR - 8184:5532:5532 plug.load_plugins:159: Failure loading found Plugin "ATEL-EDMC-latest"
Traceback (most recent call last):
  File "plug.pyc", line 157, in load_plugins
  File "plug.pyc", line 49, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Paul\\AppData\\Local\\EDMarketConnector\\plugins\\ATEL-EDMC-latest\\load.py'
2021-11-14 21:27:11.448 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "cargo-manifest-main" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\cargo-manifest-main\load.py"
2021-11-14 21:27:12.566 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "DistanceCalc" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\DistanceCalc\load.py"
2021-11-14 21:27:12.579 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "EDMC-FuelStatus-release" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMC-FuelStatus-release\load.py"
2021-11-14 21:27:12.591 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "EDMC-HourlyIncome-master" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMC-HourlyIncome-master\load.py"
2021-11-14 21:27:12.602 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "EDMC_SpanshRouter-master" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMC_SpanshRouter-master\load.py"
2021-11-14 21:27:12.864 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "EDMCHits-master" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMCHits-master\load.py"
2021-11-14 21:27:15.336 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "EDMCJumpSpeed-master" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMCJumpSpeed-master\load.py"
2021-11-14 21:27:15.336 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "EDR" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDR\load.py"
2021-11-14 21:27:15.951 - INFO - 8184:5532:5532 <plugins>.EDR.edrlog.EDRLog.log:32: Version 1.8.0
2021-11-14 21:27:16.029 - INFO - 8184:5532:5532 <plugins>.EDR.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_config.v7.ini, using config/user_igm_config.v6.ini instead.
2021-11-14 21:27:16.032 - INFO - 8184:5532:5532 <plugins>.EDR.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_config.v7.ini or config/user_igm_config.v6.ini, using config/igm_config.v7.ini instead.
2021-11-14 21:27:16.533 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "exploration-progress-1_0_4" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\exploration-progress-1.0.4\load.py"
2021-11-14 21:27:16.549 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.plugin_start:53: Exploration Progress has been loaded
2021-11-14 21:27:16.549 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "FDevIDs-master" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\FDevIDs-master\load.py"
2021-11-14 21:27:16.549 - ERROR - 8184:5532:5532 plug.Plugin.__init__:62: : Failed for Plugin "FDevIDs-master"
Traceback (most recent call last):
  File "plug.pyc", line 49, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Paul\\AppData\\Local\\EDMarketConnector\\plugins\\FDevIDs-master\\load.py'
2021-11-14 21:27:16.565 - ERROR - 8184:5532:5532 plug.load_plugins:159: Failure loading found Plugin "FDevIDs-master"
Traceback (most recent call last):
  File "plug.pyc", line 157, in load_plugins
  File "plug.pyc", line 49, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Paul\\AppData\\Local\\EDMarketConnector\\plugins\\FDevIDs-master\\load.py'
2021-11-14 21:27:16.565 - INFO - 8184:5532:5532 plug.Plugin.__init__:47: loading plugin "HabZone-master" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\HabZone-master\load.py"
2021-11-14 21:27:16.602 - INFO - 8184:5532:5532 <plugins>.EDR.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v3.ini, using config/user_igm_alt_config.v2.ini instead.
2021-11-14 21:27:16.604 - INFO - 8184:5532:5532 <plugins>.EDR.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v3.ini or config/user_igm_alt_config.v2.ini, using config/igm_alt_config.v3.ini instead.
2021-11-14 21:27:16.606 - INFO - 8184:5532:5532 <plugins>.EDR.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v3.ini, using config/user_igm_alt_config.v2.ini instead.
2021-11-14 21:27:16.608 - INFO - 8184:5532:5532 <plugins>.EDR.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v3.ini or config/user_igm_alt_config.v2.ini, using config/igm_alt_config.v3.ini instead.
2021-11-14 21:27:17.033 - ERROR - 8184:5532:5532 <plugins>.EDR.edrlog.EDRLog.log:32: Mandatory update! 1.8.0 vs. 1.8.1
2021-11-14 21:27:17.033 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_systems:137: Updating origin and destination systems...
2021-11-14 21:27:17.512 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_systems:143: Origin and destination systems updated
2021-11-14 21:27:17.513 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_status:179: Updating status...
2021-11-14 21:27:17.514 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_status:216: Status updated
2021-11-14 21:27:17.515 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_progress:149: Updating progress...
2021-11-14 21:27:17.516 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_progress:175: Progress updated
2021-11-14 21:27:18.294 - INFO - 8184:5532:5532 monitor.EDLogs.start:237: Monitoring Journal Folder: "C:\Users\Paul\Saved Games\Frontier Developments\Elite Dangerous"
2021-11-14 21:27:18.295 - INFO - 8184:5532:5532 monitor.EDLogs.start:238: Start Journal File: "C:\Users\Paul\Saved Games\Frontier Developments\Elite Dangerous\Journal.211112104937.01.log"
2021-11-14 21:29:15.389 - DEBUG - 8184:5532:5532 monitor.EDLogs.start:179: Begin...
2021-11-14 21:29:15.389 - INFO - 8184:5532:5532 monitor.EDLogs.start:237: Monitoring Journal Folder: "C:\Users\Paul\Saved Games\Frontier Developments\Elite Dangerous"
2021-11-14 21:29:15.389 - INFO - 8184:5532:5532 monitor.EDLogs.start:238: Start Journal File: "C:\Users\Paul\Saved Games\Frontier Developments\Elite Dangerous\Journal.211112104937.01.log"
2021-11-14 21:29:15.389 - DEBUG - 8184:5532:5532 monitor.EDLogs.start:247: Done.
2021-11-14 21:29:15.421 - DEBUG - 8184:5532:5532 companion.Session.login:674: already logged in (is_beta = False)
2021-11-14 21:29:15.423 - DEBUG - 8184:5532:5532 l10n._Translations.translate:172: Missing translation: 'Normal'
2021-11-14 21:29:15.424 - DEBUG - 8184:5532:5532 l10n._Translations.translate:172: Missing translation: 'Beta'
2021-11-14 21:29:15.425 - DEBUG - 8184:5532:5532 l10n._Translations.translate:172: Missing translation: 'Auto'
2021-11-14 21:29:15.645 - ERROR - 8184:5532:5532 plug.notify_prefs_changed:246: Plugin "EDMCHits-master" failed
Traceback (most recent call last):
  File "plug.pyc", line 244, in notify_prefs_changed
  File "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMCHits-master\load.py", line 138, in prefs_changed
    config.set(OVERLAY_HITS_MODE, OVERLAY_HITS_MODE.get())
  File "config.pyc", line 636, in set
TypeError: SetValueEx() argument 2 must be str or None, not StringVar
2021-11-14 21:29:15.647 - ERROR - 8184:5532:5532 <plugins>.EDR.edrlog.EDRLog.log:32: Out-of-date client, aborting.
2021-11-14 21:29:15.648 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_systems:137: Updating origin and destination systems...
2021-11-14 21:29:15.649 - DEBUG - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.get_config_str_value:127: EDMC version 5.2.1+b589ac3 should be at least 5.0.0-beta1
2021-11-14 21:29:15.649 - DEBUG - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.get_config_str_value:127: EDMC version 5.2.1+b589ac3 should be at least 5.0.0-beta1
2021-11-14 21:29:15.650 - DEBUG - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_systems:140: Origin system: Cubeo, Destination system: Colonia
2021-11-14 21:29:16.115 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_systems:143: Origin and destination systems updated
2021-11-14 21:29:16.116 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_status:179: Updating status...
2021-11-14 21:29:16.116 - DEBUG - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_status:193: Origin system not verified
2021-11-14 21:29:16.118 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_status:216: Status updated
2021-11-14 21:29:16.119 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_progress:149: Updating progress...
2021-11-14 21:29:16.119 - DEBUG - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_progress:160: 0 system(s) set
2021-11-14 21:29:16.120 - DEBUG - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_progress:171: Can't show progress at this time
2021-11-14 21:29:16.122 - INFO - 8184:5532:5532 <plugins>.exploration-progress-1.0.4.load.update_progress:175: Progress updated
2021-11-14 21:29:16.123 - DEBUG - 8184:5532:5532 l10n._Translations.translate:172: Missing translation: 'Fuel levels'
2021-11-14 21:29:16.124 - DEBUG - 8184:5532:5532 l10n._Translations.translate:172: Missing translation: 'waiting for data …'
2021-11-14 21:29:16.127 - DEBUG - 8184:5532:5532 config.AbstractConfig.getint:397: Attempt to use Deprecated getint() method
  File "EDMarketConnector.py", line 2026, in <module>
  File "tkinter\__init__.pyc", line 1429, in mainloop
  File "tkinter\__init__.pyc", line 1892, in __call__
  File "prefs.pyc", line 1271, in apply
  File "plug.pyc", line 244, in notify_prefs_changed
  File "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\HabZone-master\load.py", line 114, in prefs_changed
    update_visibility()
  File "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\HabZone-master\load.py", line 234, in update_visibility
    setting = get_setting()
  File "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\HabZone-master\load.py", line 225, in get_setting
    setting = config.getint('habzone')
  File "config.pyc", line 397, in getint
```

**Comment by DlljsCodes** [comment]
Update to [version 1.0.5](https://github.com/DlljsCodes/exploration-progress/releases/tag/v1.0.5).

**Comment by Pauliakov** [comment]
Thank you very much !
